### ISSUE TITLE
make patterns great again

### ISSUE THREAD

**Issue by muzzol** [hydrogen-music/Song-and-pattern-repository#4]
hi there!

I would like to give patterns some love.

I needed to create some patterns for my songs and I realized that that part of Hydrogen is not used/updated.

There's pages like Groove Monkee that are dedicated only to provide patterns and they make money of it.

Currently Sound Library Import don't show anything when you clic on Patterns.

My proposal is:
1- Integrate patterns correctly with Hydrogen as a downloadable repo or directly with the package. Maybe starting next version could be integrated in the package or suggest distro packagers to create an additional package (hydrogen-patterns)

2- Improve pattern workflow. Clicking on a pattern should give the option to listen to it even if not loaded so you can see if it fits your need. Also double clicking should load the pattern and focus on it. Pattern library could be near pattern list instead of the opposite corner with a quick show/hide button so you can load them quickly.

3- Patterns should be kit agnostics. Sometimes I discard a pattern because it sound bad and later I found is because it was created with another kit so elements get mixed. This shouldn't happen. Also it would be great to be able to import midi directly. I know this have been discussed in the past and maybe is a good time to start.

4- Autoload patterns on new song. When you create a  song ask if you want an empty pattern or if you want to start with some genre specific pattern.

5- More patterns! We need tons of patterns here. Maybe we could show some hint to encourage people to share their patterns. Maybe some anual contest with actual prizes. Also, could be great to be able to upload patterns to a public repo directly from the app.

Overall, I think we need to improve that area and even make it more prominent.  
I can offer a server to host a free repo and I can do some other work on the server side (I'm linux sysadmin).

**Comment by trebmuh** [comment]
@muzzol you should come and discuss that on the -dev. I'm personnaly not a fan of repo's issue with multiple suggestion/FR/issue in it, since they soon will become a flooding impossible-to-read-everything-in-less-than-1-hour thread.

**Comment by muzzol** [comment]
@trebmuh totally agree.

I just subscribed to ML and will send a message soon.

**Comment by trebmuh** [comment]
Thanks. Can I close this thread then?

**Comment by muzzol** [comment]
sure, message already sent to list.

thanks for your time, olivier.
